### ISSUE TITLE
Aligning paragraph text to top of image 

### ISSUE THREAD

**Issue by kaybow** [kaybow/dsn1674-assignment-5#1]
I've watched the video "Float & Clear: wrapped image", and targeted my paragraph in CSS to align my text to the top of the image grains.jpg. When I set the margin-top to 0, it brings my image up as well as the text. I've even tried adding a class to the first paragraph, and the same thing happens.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Have you tried putting a margin on the top of the `img` to push it down a little?

**Comment by kaybow** [comment]
No, that's far too simple a solution...it worked, of course. Thanks for your patience with me.
